会場を株式会社インプレスに更新した
rkawabuchi/ichiyasaGitSample pull request #1
Opened 2024-03-15 16:20 UTC by rkawabuchi

### 変更内相
イベント開催会場を「株式会社インプレス」に更新しました。

###  背景
「株式会社インプレス」様がイベント会場を提供してくださることになりました。

2024-03-15 16:23 UTC, RyoheiK commented
ありがとうございます！問題ないのでマージします。

2024-03-16 08:02 UTC, RyoheiK requested changes
修正希望が一点あります。よろしくお願いします。

2024-03-16 08:02 UTC, RyoheiK commented on index.html
> +                        <p>3月26日 19:00開始</p>
開催日は3月31日になったと思います。確認をお願いします。

2024-03-16 08:03 UTC, rkawabuchi commented on index.html
> +                        <p>3月26日 19:00開始</p>
ご指摘の通りと確認できました。修正します。

2024-03-16 08:07 UTC, RyoheiK approved these changes
修正されていることを確認しました！ありがとうございます。

2024-03-16 08:10 UTC, merged